# Generated by Django 3.2.22 on 2023-10-28 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('model', models.CharField(choices=[('m1', 'M1'), ('1m', '1M Coupe'), ('m2', 'M2'), ('m3', 'M3'), ('m4', 'M4'), ('m5', 'M5'), ('m6', 'M6'), ('m8', 'M8')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('bhp', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('is_modified', models.BooleanField(default=False)),
                ('colour', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='../ultimate-m-car/default_post_xq3ozj', upload_to='images/')),
                ('image_filter', models.CharField(choices=[('m1', 'M1'), ('1m', '1M Coupe'), ('m2', 'M2'), ('m3', 'M3'), ('m4', 'M4'), ('m5', 'M5'), ('m6', 'M6'), ('m8', 'M8')], default='normal', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
