# Generated by Django 3.2.22 on 2023-11-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bhp',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='colour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='model',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
