# Generated by Django 3.2.22 on 2023-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20231113_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_modified',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
