# Generated by Django 3.2.22 on 2023-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../ultimate_m_car/default_profile_frq4az', upload_to='images/'),
        ),
    ]
