# Generated by Django 3.2.22 on 2023-11-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.TextField(blank=True),
        ),
    ]
