# Generated by Django 3.2.22 on 2023-11-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
    ]
